feature = [
    'day', 'register_type', 'device_type', 'app_min', 'app_max', 'app_mean', 'app_median', 'app_skew',
    'app_std', 'app_mad', 'app_count', 'app_ptp', 'app_var', 'app_var_divide_count', 'app_last_one', 'app_q25',
    'app_q75', 'app_kurt', 'video_min', 'video_max', 'video_mean', 'video_median', 'video_skew', 'video_std',
    'video_mad', 'video_count', 'video_ptp', 'video_var', 'video_var_divide_count', 'video_last_one', 'video_q25',
    'video_q75', 'video_kurt', 'act_min', 'act_max', 'act_mean', 'act_median', 'act_skew', 'act_std', 'act_mad',
    'act_count', 'act_ptp', 'act_var', 'act_var_divide_count', 'act_last_one', 'act_q25', 'act_q75', 'act_kurt',
    'app_last_minus_reg', 'video_last_minus_reg', 'act_last_minus_reg', 'pastday4', 'pastday3', 'pastday2',
    'pastday1', 'pastday0', 'past4_ptype0', 'past4_ptype1', 'past4_ptype2', 'past4_ptype3', 'past4_ptype4',
    'past3_ptype0', 'past3_ptype1', 'past3_ptype2', 'past3_ptype3', 'past3_ptype4', 'past2_ptype0', 'past2_ptype1',
    'past2_ptype2', 'past2_ptype3', 'past2_ptype4', 'past1_ptype0', 'past1_ptype1', 'past1_ptype2', 'past1_ptype3',
    'past1_ptype4', 'past0_ptype0', 'past0_ptype1', 'past0_ptype2', 'past0_ptype3', 'past0_ptype4', 'past4_atype0',
    'past4_atype1', 'past4_atype2', 'past4_atype3', 'past4_atype4', 'past4_atype5', 'past3_atype0', 'past3_atype1',
    'past3_atype2', 'past3_atype3', 'past3_atype4', 'past3_atype5', 'past2_atype0', 'past2_atype1', 'past2_atype2',
    'past2_atype3', 'past2_atype4', 'past2_atype5', 'past1_atype0', 'past1_atype1', 'past1_atype2', 'past1_atype3',
    'past1_atype4', 'past1_atype5', 'past0_atype0', 'past0_atype1', 'past0_atype2', 'past0_atype3', 'past0_atype4',
    'past0_atype5', '0_page_count', '1_page_count', '2_page_count', '3_page_count', '4_page_count', '0_act_count',
    '1_act_count', '2_act_count', '3_act_count', '4_act_count', '5_act_count', 'page_stat_min', 'page_stat_max',
    'page_stat_mean', 'page_stat_median', 'page_stat_skew', 'page_stat_std', 'page_stat_mad', 'page_stat_count',
    'page_stat_ptp', 'page_stat_var', 'page_stat_var_divide_count', 'page_stat_last_one', 'page_stat_q25',
    'page_stat_q75', 'page_stat_kurt', 'act_stat_min', 'act_stat_max', 'act_stat_mean', 'act_stat_median',
    'act_stat_skew', 'act_stat_std', 'act_stat_mad', 'act_stat_count', 'act_stat_ptp', 'act_stat_var',
    'act_stat_var_divide_count', 'act_stat_last_one', 'act_stat_q25', 'act_stat_q75', 'act_stat_kurt', 'author_id_min',
    'author_id_max', 'author_id_mean', 'author_id_median', 'author_id_skew', 'author_id_std', 'author_id_mad',
    'author_id_count', 'author_id_ptp', 'author_id_var', 'author_id_var_divide_count', 'author_id_last_one',
    'author_id_q25', 'author_id_q75', 'author_id_kurt', 'video_id_min', 'video_id_max', 'video_id_mean',
    'video_id_median', 'video_id_skew', 'video_id_std', 'video_id_mad', 'video_id_count', 'video_id_ptp',
    'video_id_var', 'video_id_var_divide_count', 'video_id_last_one', 'video_id_q25', 'video_id_q75', 'video_id_kurt'
]
